name: Build and Test (Windows Debug)

on:
  push:

jobs:
  build-windows-debug:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure and build (Debug)
      run: |
        cmake -S . -B build-windows-debug -DDECENTRALISED_ART_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=install-windows-debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build-windows-debug --config Debug --target DecentralisedArtServerTests -j 4

    - name: Run tests
      run: ctest --test-dir build-windows-debug/tests -C Debug --output-on-failure

    - name: Install artifacts
      run: cmake --build build-windows-debug --config Debug --target install -j 4

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: decentralised-art-server-windows-debug
        path: install-windows-debug
