name: Build Decentralised Art Server

on:
  workflow_run:
    workflows: ["Build and Test (Debug)"]
    types: [completed]
    branches: [ main ]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake build-essential libssl-dev npm

    - name: Configure and build (Release)
      run: |
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target install -j 4

    - name: Pack install directory into tarball
      run: |
        tar -czf decentralised-art-server.tar.gz -C install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: decentralised-art-server
        path: decentralised-art-server.tar.gz 
